# Generated by Django 5.0.6 on 2024-10-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
