# Generated by Django 5.0.6 on 2024-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_personaldetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
